#!/bin/bash

# Production Environment Variables Update Script
# Run this to update Railway environment variables for email fix

echo "📧 Email Configuration Fix - Production Update"
echo "=============================================="
echo ""
echo "⚠️  IMPORTANT: Update these environment variables in Railway:"
echo ""
echo "1. Go to: https://railway.app/project/[your-project-id]/settings"
echo "2. Click on 'Variables' tab"
echo "3. Update or add these variables:"
echo ""
echo "Required SMTP Variables:"
echo "------------------------"
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_PORT=587"
echo "SMTP_USER=mlcorporateservicesit@gmail.com"
echo "SMTP_PASS=fksgpuujhqtqrsdr    # ⚠️ REMOVE SPACES! (was: 'fksg puuj hqtq rsdr')"
echo "SMTP_FROM_EMAIL=noreply@toolbay.store"
echo "SMTP_FROM_NAME=Toolbay"
echo ""
echo "Optional (can keep or remove):"
echo "------------------------------"
echo "RESEND_API_KEY=<YOUR_RESEND_API_KEY>  # No longer used"
echo ""
echo "=============================================="
echo ""
echo "Steps to Update:"
echo "----------------"
echo "1. ✅ Code changes pushed to GitHub (done)"
echo "2. ⏳ Update Railway environment variables (do this now)"
echo "3. ⏳ Wait for automatic deployment or trigger manually"
echo "4. ⏳ Test registration email: https://toolbay.net/sign-up"
echo "5. ⏳ Test password reset: https://toolbay.net/forgot-password"
echo ""
echo "Most Important Change:"
echo "----------------------"
echo "Change SMTP_PASS from: fksg puuj hqtq rsdr"
echo "                  to: fksgpuujhqtqrsdr"
echo "                      (remove all spaces)"
echo ""
echo "After updating variables, Railway will automatically redeploy."
echo "Wait ~2-3 minutes for deployment to complete."
echo ""
echo "Test Email Delivery:"
echo "--------------------"
echo "Visit: https://toolbay.net/test-email"
echo "Click 'Send Test Email' to verify configuration"
echo ""
